export const navItems = [
  { label: "Overview", href: "#" },
  { label: "People", href: "#" },
  { label: "Timeoff", href: "#" },
  { label: "Holidays", href: "#" },
  { label: "Benefits", href: "#" },
  { label: "Trainings", href: "#" },
  { label: "Onboarding", href: "#" },
  { label: "Documents", href: "#" },
  { label: "Reports", href: "#" },
  { label: "Tasks", href: "#" },
  { label: "Settings", href: "#" },
];

interface Leave {
  sickLeave: number;
  travelLeave: number;
  annualLeave: number;
}

interface Employee {
  name: string;
  dob: string;
  dateOfResumption: string;
  dateOfLeave: string;
  dateOfStart: string;
  position: string;
  department: string;
  gender: string;
  leaves: Leave;
  isNew: boolean;
  isPresent: boolean;
}

const employees = [
  {
    name: "John Doe",
    dob: "1985-01-15",
    dateOfResumption: "2022-01-01",
    dateOfLeave: "2023-01-01",
    dateOfStart: "2022-01-01",
    position: "Software Engineer",
    department: "Engineering",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Jane Smith",
    dob: "1990-03-22",
    dateOfResumption: "2022-02-15",
    dateOfLeave: "2023-02-15",
    dateOfStart: "2022-02-15",
    position: "Product Manager",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Alice Johnson",
    dob: "1988-07-11",
    dateOfResumption: "2022-03-10",
    dateOfLeave: "2023-03-10",
    dateOfStart: "2022-03-10",
    position: "Designer",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Bob Brown",
    dob: "1992-11-08",
    dateOfResumption: "2022-04-01",
    dateOfLeave: "2023-04-01",
    dateOfStart: "2022-04-01",
    position: "Developer",
    department: "Engineering",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Michael Green",
    dob: "1987-04-05",
    dateOfResumption: "2021-06-15",
    dateOfLeave: "2022-06-15",
    dateOfStart: "2021-06-15",
    position: "DevOps Engineer",
    department: "Engineering",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Rachel Adams",
    dob: "1993-08-17",
    dateOfResumption: "2021-09-01",
    dateOfLeave: "2022-09-01",
    dateOfStart: "2021-09-01",
    position: "QA Engineer",
    department: "Engineering",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Emily Clark",
    dob: "1995-05-29",
    dateOfResumption: "2021-12-10",
    dateOfLeave: "2022-12-10",
    dateOfStart: "2021-12-10",
    position: "Business Analyst",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: true,
  },
  {
    name: "Daniel White",
    dob: "1983-02-21",
    dateOfResumption: "2022-01-25",
    dateOfLeave: "2023-01-25",
    dateOfStart: "2022-01-25",
    position: "Scrum Master",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Chloe Martinez",
    dob: "1991-06-19",
    dateOfResumption: "2021-08-14",
    dateOfLeave: "2022-08-14",
    dateOfStart: "2021-08-14",
    position: "UI/UX Designer",
    department: "Design",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "James Wilson",
    dob: "1989-11-27",
    dateOfResumption: "2021-10-09",
    dateOfLeave: "2022-10-09",
    dateOfStart: "2021-10-09",
    position: "Backend Developer",
    department: "Engineering",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "Laura Davis",
    dob: "1994-03-03",
    dateOfResumption: "2022-02-03",
    dateOfLeave: "2023-02-03",
    dateOfStart: "2022-02-03",
    position: "Frontend Developer",
    department: "Engineering",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: true,
  },
  {
    name: "David Moore",
    dob: "1986-07-24",
    dateOfResumption: "2022-05-19",
    dateOfLeave: "2023-05-19",
    dateOfStart: "2022-05-19",
    position: "Project Manager",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "Samantha Taylor",
    dob: "1997-01-12",
    dateOfResumption: "2021-11-25",
    dateOfLeave: "2022-11-25",
    dateOfStart: "2021-11-25",
    position: "Marketing Specialist",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: true,
  },
  {
    name: "Christopher Brown",
    dob: "1992-10-01",
    dateOfResumption: "2021-07-18",
    dateOfLeave: "2022-07-18",
    dateOfStart: "2021-07-18",
    position: "System Administrator",
    department: "IT",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "Isabella Harris",
    dob: "1996-05-10",
    dateOfResumption: "2021-09-28",
    dateOfLeave: "2022-09-28",
    dateOfStart: "2021-09-28",
    position: "Content Writer",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Alexander Johnson",
    dob: "1984-12-02",
    dateOfResumption: "2022-03-15",
    dateOfLeave: "2023-03-15",
    dateOfStart: "2022-03-15",
    position: "Security Engineer",
    department: "IT",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "Emma Walker",
    dob: "1998-04-27",
    dateOfResumption: "2021-10-12",
    dateOfLeave: "2022-10-12",
    dateOfStart: "2021-10-12",
    position: "HR Specialist",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 4,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Andrew Martinez",
    dob: "1991-11-05",
    dateOfResumption: "2021-06-30",
    dateOfLeave: "2022-06-30",
    dateOfStart: "2021-06-30",
    position: "Data Analyst",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Olivia Anderson",
    dob: "1988-08-13",
    dateOfResumption: "2022-04-05",
    dateOfLeave: "2023-04-05",
    dateOfStart: "2022-04-05",
    position: "Operations Manager",
    department: "operations",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Daniel Thomas",
    dob: "1993-02-19",
    dateOfResumption: "2021-07-01",
    dateOfLeave: "2022-07-01",
    dateOfStart: "2021-07-01",
    position: "Technical Lead",
    department: "Engineering",
    gender: "male",
    leaves: {
      sickLeave: 4,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Mia White",
    dob: "1995-12-24",
    dateOfResumption: "2022-05-20",
    dateOfLeave: "2023-05-20",
    dateOfStart: "2022-05-20",
    position: "Customer Support",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Jacob Lewis",
    dob: "1983-03-11",
    dateOfResumption: "2021-08-22",
    dateOfLeave: "2022-08-22",
    dateOfStart: "2021-08-22",
    position: "IT ",
    department: "IT",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Sophia King",
    dob: "1990-09-29",
    dateOfResumption: "2022-02-01",
    dateOfLeave: "2023-02-01",
    dateOfStart: "2022-02-01",
    position: "SEO Specialist",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "William Scott",
    dob: "1986-11-12",
    dateOfResumption: "2021-09-10",
    dateOfLeave: "2022-09-10",
    dateOfStart: "2021-09-10",
    position: "Copywriter",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Grace Young",
    dob: "1997-07-15",
    dateOfResumption: "2021-12-01",
    dateOfLeave: "2022-12-01",
    dateOfStart: "2021-12-01",
    position: "Sales Manager",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Benjamin Hernandez",
    dob: "1989-05-18",
    dateOfResumption: "2022-01-25",
    dateOfLeave: "2023-01-25",
    dateOfStart: "2022-01-25",
    position: "Graphic Designer",
    department: "Design",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Victoria Clark",
    dob: "1994-02-06",
    dateOfResumption: "2021-10-03",
    dateOfLeave: "2022-10-03",
    dateOfStart: "2021-10-03",
    position: "Content Manager",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "David Perez",
    dob: "1987-08-23",
    dateOfResumption: "2021-11-15",
    dateOfLeave: "2022-11-15",
    dateOfStart: "2021-11-15",
    position: "Financial Analyst",
    department: "Finance",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Natalie Martinez",
    dob: "1991-06-25",
    dateOfResumption: "2022-04-22",
    dateOfLeave: "2023-04-22",
    dateOfStart: "2022-04-22",
    position: "Research Analyst",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Ethan Turner",
    dob: "1985-12-11",
    dateOfResumption: "2021-08-29",
    dateOfLeave: "2022-08-29",
    dateOfStart: "2021-08-29",
    position: "Legal Advisor",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Amelia Lopez",
    dob: "1993-03-09",
    dateOfResumption: "2021-11-30",
    dateOfLeave: "2022-11-30",
    dateOfStart: "2021-11-30",
    position: "Accountant",
    department: "Finance",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: true,
  },
  {
    name: "Samuel Hill",
    dob: "1988-07-07",
    dateOfResumption: "2022-03-18",
    dateOfLeave: "2023-03-18",
    dateOfStart: "2022-03-18",
    position: "HR Manager",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 0,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: true,
    isNew: false,
  },
  {
    name: "Ava Scott",
    dob: "1996-09-12",
    dateOfResumption: "2021-10-26",
    dateOfLeave: "2022-10-26",
    dateOfStart: "2021-10-26",
    position: "Office Manager",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 4,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "Matthew Lewis",
    dob: "1990-01-19",
    dateOfResumption: "2022-05-07",
    dateOfLeave: "2023-05-07",
    dateOfStart: "2022-05-07",
    position: "Recruiter",
    department: "",
    gender: "male",
    leaves: {
      sickLeave: 2,
      travelLeave: 0,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
  {
    name: "Zoe Walker",
    dob: "1983-04-04",
    dateOfResumption: "2021-08-10",
    dateOfLeave: "2022-08-10",
    dateOfStart: "2021-08-10",
    position: "Training Coordinator",
    department: "",
    gender: "female",
    leaves: {
      sickLeave: 0,
      travelLeave: 1,
      annualLeave: 0,
    },
    isPresent: false,
    isNew: false,
  },
];

export default employees;
